### PR TITLE
Fix "Cannot read property 'trim' of undefined" for Hipchat unread js

### PR DESCRIPTION
**Pull request by ThauEx**

### CODE REVIEW

**Comment by TheGoddessInari** [comment]
I'll check on this, but the code iterates over the found elements. So is the problem that you can have an `.hc-badge` with no innerHTML? 

The second commit doesn't make any sense. i is the current element, not the iterator.

**Comment by ThauEx** [comment]
> The second commit doesn't make any sense. i is the current element, not the iterator.
Not really, but I noticed the issue. The variable `e` is an array, but for…in is being used, which is for objects, so `i` is the key, a change to for…of would fix it and `i` would be the element then. Maybe this fixes the innerHTML issue too. Will do a fix/test later.

**Comment by TheGoddessInari** [comment]
That's weird, I'm pretty sure I had a linter rule specifically for this case (for in vs. for of), I pushed a commit to testing that replaces the 3 cases. See if that helps. It should, I'll try to figure out how this case slipped through the cracks.

**Comment by ThauEx** [comment]
I tested only hipchat, but with for…of it's working fine.

**Pull request closed without merging**
